'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import './style.css';

const session=()=>{let id=localStorage.getItem('cm_session_id');if(!id){id=crypto.randomUUID();localStorage.setItem('cm_session_id',id)}return id};
const track=(event:string,properties:Record<string,unknown>={})=>fetch('/api/cm/track',{method:'POST',headers:{'Content-Type':'application/json',...(localStorage.getItem('cm_access_token')?{Authorization:`Bearer ${localStorage.getItem('cm_access_token')}`}:{})},body:JSON.stringify({event,sessionId:session(),properties})}).catch(()=>{});

export default function AlphaInvite(){
 const [code,setCode]=useState('');const [state,setState]=useState<'idle'|'working'|'done'|'error'>('idle');const [bonus,setBonus]=useState(0);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const c=(q.get('code')||'').toUpperCase();setCode(c);track('alpha_invite_view',{hasCode:Boolean(c)})},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!code||state==='working')return;const token=localStorage.getItem('cm_access_token');if(!token){localStorage.setItem('cm_alpha_invite',code);window.location.href=`/che-mira-v5/acceso?next=${encodeURIComponent('/che-mira-v5/alpha?code='+code)}`;return}setState('working');const r=await fetch('/api/cm/alpha/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({code})});const x=await r.json().catch(()=>({}));if(r.ok){setBonus(Number(x.data?.bonus_free_posts||0));setState('done');track('alpha_invite_redeemed',{bonus:Number(x.data?.bonus_free_posts||0)});localStorage.removeItem('cm_alpha_invite')}else setState('error')};
 return <main className="alphaInvite"><header><Link href="/che-mira-v5">CHE, MIRÁ</Link><span>ALPHA ORGANIZADORES</span></header><section className="alphaHero"><div><span>BUENOS AIRES · ALPHA</span><h1>Traé algo<br/>que merezca<br/>ser visto.</h1></div><p>Estamos armando la primera capa de oferta de Che, Mirá con organizadores reales. Si te invitaron, activá tu código y empezá a publicar.</p></section>{state==='done'?<section className="alphaDone"><span>INVITACIÓN ACTIVADA</span><h2>{bonus} publicaciones extra gratis.</h2><p>Tu cuenta conserva además la regla de pricing experimental que le haya tocado. Este bonus sólo existe para acelerar la alpha.</p><div><Link href="/che-mira-v5/publicar">Publicar ahora →</Link><Link href="/che-mira-v5/mi-perfil">Armar mi agenda pública</Link></div></section>:<form onSubmit={submit} className="alphaCode"><label><span>CÓDIGO DE INVITACIÓN</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="CMXXXXXX" autoFocus/></label><button disabled={!code||state==='working'}>{state==='working'?'Activando…':'Activar acceso alpha →'}</button>{state==='error'&&<p>Ese código no está disponible, venció o ya alcanzó su cupo.</p>}</form>}<section className="alphaWhy"><article><b>1.</b><h3>Publicá.</h3><p>Evento, menú, fecha especial, taller, fiesta o experiencia.</p></article><article><b>2.</b><h3>Compartí.</h3><p>Usá tu ficha de Che, Mirá como agenda y traé tu propia audiencia.</p></article><article><b>3.</b><h3>Competí.</h3><p>Si querés más atención, Ojo Acá te deja comprar una posición visible.</p></article></section></main>
}
