'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import './style.css';

type Status='ACTIVAS'|'PRÓXIMAS'|'VENCIDAS';
type ApiPub={id:string;slug:string;title:string;starts_at:string;expires_at:string;neighborhood:string;price_label:string|null;published_at:string;status:string;views:number;clicks:number;ojo:null|{market_key:string;amount_minor:number}};
type Pub={id:string;status:Status;title:string;date:string;place:string;published:string;views:number;clicks:number;price:string;promoted:boolean;market?:string;rawStatus:string};
const dateKey=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const formatDate=(iso:string)=>new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)).replace(',',' ·').toUpperCase();
const ago=(iso:string)=>{const m=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(m<60)return `hace ${Math.max(1,m)} min`;const h=Math.floor(m/60);return h<24?`hace ${h} h`:`hace ${Math.floor(h/24)} días`};
const mapPub=(x:ApiPub):Pub=>{const now=new Date();const expired=x.status!=='active'||new Date(x.expires_at)<now;const today=dateKey(now);const eventDay=dateKey(new Date(x.starts_at));const status:Status=expired?'VENCIDAS':eventDay===today?'ACTIVAS':'PRÓXIMAS';return{id:x.slug,status,title:x.title,date:formatDate(x.starts_at),place:x.neighborhood,published:ago(x.published_at),views:x.views||0,clicks:x.clicks||0,price:x.price_label||'Consultar',promoted:Boolean(x.ojo),market:x.ojo?.market_key,rawStatus:x.status}};

export default function MisPublicaciones(){
  const [status,setStatus]=useState<Status>('ACTIVAS');const [data,setData]=useState<Pub[]>([]);const [loading,setLoading]=useState(true);const [needsAuth,setNeedsAuth]=useState(false);const [message,setMessage]=useState('');
  const load=()=>{const token=localStorage.getItem('cm_access_token');if(!token){setNeedsAuth(true);setLoading(false);return}setLoading(true);fetch('/api/cm/mine',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(r.status===401){localStorage.removeItem('cm_access_token');setNeedsAuth(true);return null}return r.ok?r.json():Promise.reject()}).then(x=>{if(x?.data)setData(x.data.map(mapPub))}).catch(()=>setMessage('No pudimos actualizar tus publicaciones.')).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  const rows=useMemo(()=>data.filter(x=>x.status===status),[data,status]);const active=data.filter(x=>x.status!=='VENCIDAS').length;const views=data.reduce((n,x)=>n+x.views,0);const clicks=data.reduce((n,x)=>n+x.clicks,0);
  const cancel=async(slug:string,title:string)=>{if(!window.confirm(`¿Cancelar “${title}”? Deja de aparecer en el feed y en Explorar.`))return;const token=localStorage.getItem('cm_access_token');if(!token)return;const res=await fetch(`/api/cm/listings/${encodeURIComponent(slug)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'cancel'})});if(res.ok){setMessage('Publicación cancelada.');load()}else setMessage('No pudimos cancelar la publicación.')};
  const share=async(slug:string,title:string)=>{const url=`${window.location.origin}/che-mira-v5/p/${slug}?from=publisher`;if(navigator.share){await navigator.share({title,url}).catch(()=>{})}else{await navigator.clipboard?.writeText(url);setMessage('Link copiado.')}};
  const logout=()=>{localStorage.removeItem('cm_access_token');localStorage.removeItem('cm_refresh_token');localStorage.removeItem('cm_user_id');window.location.href='/che-mira-v5'};

  return <main className="myPub"><header className="myTop"><Link href="/che-mira-v5" className="myLogo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v5/guardados">Mis planes</Link><button onClick={logout}>Salir</button><Link href="/che-mira-v5/publicar" className="newPub">+ Nueva publicación</Link></nav></header>
    <section className="myHero"><div><span>PARA QUIEN PUBLICA</span><h1>Mis publicaciones.</h1></div><div className="summary"><p><b>{active}</b><span>vigentes</span></p><p><b>{views}</b><span>visitas</span></p><p><b>{clicks}</b><span>clicks afuera</span></p></div></section>
    {message&&<section className="noRows">{message}</section>}
    {needsAuth?<section className="noRows"><b>Necesitás entrar para ver tus publicaciones.</b><br/><br/><Link href="/che-mira-v5/acceso?next=/che-mira-v5/mis-publicaciones">Entrar →</Link></section>:<><section className="statusTabs">{(['ACTIVAS','PRÓXIMAS','VENCIDAS'] as Status[]).map(x=><button key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x}</button>)}</section><section className="pubTable"><div className="tableHead"><span>PUBLICACIÓN</span><span>RENDIMIENTO</span><span>ACCIONES</span></div>{loading&&<div className="noRows">Cargando…</div>}{!loading&&rows.map(x=><article key={x.id}><div className="pubInfo"><div className="pubFlags"><span>{x.date}</span>{x.promoted&&<b>OJO ACÁ · {x.market}</b>}{x.rawStatus==='cancelled'&&<b>CANCELADA</b>}</div><h2>{x.title}</h2><p>{x.place} · {x.price}</p><small>Publicado {x.published}. Editar no cambia esta antigüedad.</small></div><div className="pubMetrics"><p><b>{x.views}</b><span>visitas</span></p><p><b>{x.clicks}</b><span>clicks afuera</span></p><p><b>{x.views?Math.round(x.clicks/x.views*100):0}%</b><span>CTR</span></p></div><div className="pubActions"><Link href={`/che-mira-v5/p/${x.id}`}>Ver ↗</Link>{status!=='VENCIDAS'&&<Link href={`/che-mira-v5/publicar?edit=${encodeURIComponent(x.id)}`}>Editar</Link>}<button onClick={()=>share(x.id,x.title)}>Compartir</button><Link href={`/che-mira-v5/publicar?duplicate=${encodeURIComponent(x.id)}`}>Repetir</Link>{status!=='VENCIDAS'&&<Link className="attention" href={`/che-mira-v5/ojo?listing=${encodeURIComponent(x.id)}`}>{x.promoted?'Subir posición':'Dar más atención'}</Link>}{status!=='VENCIDAS'&&<button className="cancel" onClick={()=>cancel(x.id,x.title)}>Cancelar</button>}</div></article>)}{!loading&&rows.length===0&&<div className="noRows">No hay publicaciones en este estado.</div>}</section></>}
    <section className="dashboardRule"><span>REGLA DEL FEED</span><h2>Podés corregir. No podés volver a nacer.</h2><p>Editar mantiene intacto el momento original de publicación. Si el evento se repite, “Repetir” crea una publicación nueva para la próxima fecha.</p></section></main>
}
