'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import './style.css';

type Status='ACTIVAS'|'PRÓXIMAS'|'VENCIDAS';
type ApiPub={id:string;slug:string;title:string;starts_at:string;expires_at:string;neighborhood:string;price_label:string|null;published_at:string;status:string;views:number;clicks:number;publisher_views:number;share_views:number;ojo:null|{market_key:string;amount_minor:number;rank:number|null}};
type Pub={id:string;status:Status;title:string;date:string;place:string;published:string;views:number;clicks:number;publisherViews:number;shareViews:number;price:string;promoted:boolean;market?:string;rank?:number|null;rawStatus:string;startsAt:string};
type Summary={views:number;clicks:number;publisher_views:number;share_views:number};
const dateKey=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const formatDate=(iso:string)=>new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)).replace(',',' ·').toUpperCase();
const ago=(iso:string)=>{const m=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(m<60)return `hace ${Math.max(1,m)} min`;const h=Math.floor(m/60);return h<24?`hace ${h} h`:`hace ${Math.floor(h/24)} días`};
const mapPub=(x:ApiPub):Pub=>{const now=new Date();const expired=x.status!=='active'||new Date(x.expires_at)<now;const today=dateKey(now);const eventDay=dateKey(new Date(x.starts_at));const status:Status=expired?'VENCIDAS':eventDay===today?'ACTIVAS':'PRÓXIMAS';return{id:x.slug,status,title:x.title,date:formatDate(x.starts_at),place:x.neighborhood,published:ago(x.published_at),views:x.views||0,clicks:x.clicks||0,publisherViews:x.publisher_views||0,shareViews:x.share_views||0,price:x.price_label||'Consultar',promoted:Boolean(x.ojo),market:x.ojo?.market_key,rank:x.ojo?.rank,rawStatus:x.status,startsAt:x.starts_at}};

export default function MisPublicaciones(){
  const [status,setStatus]=useState<Status>('ACTIVAS');const [data,setData]=useState<Pub[]>([]);const [summary,setSummary]=useState<Summary>({views:0,clicks:0,publisher_views:0,share_views:0});const [loading,setLoading]=useState(true);const [needsAuth,setNeedsAuth]=useState(false);const [message,setMessage]=useState('');
  const load=()=>{const token=localStorage.getItem('cm_access_token');if(!token){setNeedsAuth(true);setLoading(false);return}setLoading(true);fetch('/api/cm/mine',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(r.status===401){localStorage.removeItem('cm_access_token');setNeedsAuth(true);return null}return r.ok?r.json():Promise.reject()}).then(x=>{if(x?.data){setData(x.data.map(mapPub));setSummary(x.summary||summary)}}).catch(()=>setMessage('No pudimos actualizar tus publicaciones.')).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  const rows=useMemo(()=>data.filter(x=>x.status===status),[data,status]);const active=data.filter(x=>x.status!=='VENCIDAS').length;const expired=data.filter(x=>x.status==='VENCIDAS').slice(0,3);const urgent=data.filter(x=>x.status!=='VENCIDAS'&&new Date(x.startsAt).getTime()-Date.now()<48*3600000&&new Date(x.startsAt).getTime()>Date.now()).slice(0,3);
  const cancel=async(slug:string,title:string)=>{if(!window.confirm(`¿Cancelar “${title}”? Deja de aparecer en el feed y en Explorar.`))return;const token=localStorage.getItem('cm_access_token');if(!token)return;const res=await fetch(`/api/cm/listings/${encodeURIComponent(slug)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'cancel'})});if(res.ok){setMessage('Publicación cancelada.');load()}else setMessage('No pudimos cancelar la publicación.')};
  const share=async(slug:string,title:string)=>{const url=`${window.location.origin}/che-mira-v5/p/${slug}?src=publisher`;if(navigator.share){await navigator.share({title,url}).catch(()=>{})}else{await navigator.clipboard?.writeText(url);setMessage('Link copiado.')}};
  const logout=()=>{localStorage.removeItem('cm_access_token');localStorage.removeItem('cm_refresh_token');localStorage.removeItem('cm_user_id');window.location.href='/che-mira-v5'};

  return <main className="myPub"><header className="myTop"><Link href="/che-mira-v5" className="myLogo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v5/reclamar">Reclamar</Link><Link href="/che-mira-v5/guardados">Mis planes</Link><button onClick={logout}>Salir</button><Link href="/che-mira-v5/publicar" className="newPub">+ Nueva publicación</Link></nav></header>
    <section className="myHero"><div><span>PARA QUIEN PUBLICA</span><h1>Mis publicaciones.</h1></div><div className="summary"><p><b>{active}</b><span>vigentes</span></p><p><b>{summary.views}</b><span>visitas</span></p><p><b>{summary.clicks}</b><span>clicks afuera</span></p><p><b>{summary.publisher_views}</b><span>las trajiste vos</span></p></div></section>
    {!loading&&(urgent.length>0||expired.length>0)&&<section className="retentionGrid">{urgent.length>0&&<article className="retentionHot"><span>PRÓXIMAS 48 HORAS</span><h2>No esperes al feed.</h2><p>Tu evento ya está cerca. Compartí la ficha con tu audiencia o comprá atención si querés sostener visibilidad.</p><div>{urgent.map(x=><div key={x.id}><b>{x.title}</b><span>{x.date}</span><button onClick={()=>share(x.id,x.title)}>Compartir</button><Link href={`/che-mira-v5/ojo?listing=${encodeURIComponent(x.id)}`}>{x.promoted?`Ojo #${x.rank||'—'}`:'Entrar a Ojo'}</Link></div>)}</div></article>}{expired.length>0&&<article><span>VOLVER A PUBLICAR</span><h2>¿Se repite?</h2><p>Usá una publicación vencida como plantilla. Cambiás la fecha y vuelve a entrar como una publicación nueva.</p><div>{expired.map(x=><div key={x.id}><b>{x.title}</b><span>{x.views} visitas · {x.clicks} clicks</span><Link href={`/che-mira-v5/publicar?duplicate=${encodeURIComponent(x.id)}`}>Próxima fecha →</Link></div>)}</div></article>}</section>}
    <section className="originStrip"><div><span>TRÁFICO QUE TRAJISTE</span><b>{summary.publisher_views}</b><p>visitas llegaron desde links que compartiste vos.</p></div><div><span>OTROS SHARES</span><b>{summary.share_views}</b><p>visitas llegaron desde el botón Compartir de la ficha.</p></div><Link href="/che-mira-v5/reclamar"><span>¿YA HABÍA FECHAS TUYAS?</span><b>Reclamalas juntas.</b><p>Buscá varias publicaciones comunitarias y pedí control en un solo paso →</p></Link></section>
    {message&&<section className="noRows">{message}</section>}
    {needsAuth?<section className="noRows"><b>Necesitás entrar para ver tus publicaciones.</b><br/><br/><Link href="/che-mira-v5/acceso?next=/che-mira-v5/mis-publicaciones">Entrar →</Link></section>:<><section className="statusTabs">{(['ACTIVAS','PRÓXIMAS','VENCIDAS'] as Status[]).map(x=><button key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x}</button>)}</section><section className="pubTable"><div className="tableHead"><span>PUBLICACIÓN</span><span>RENDIMIENTO</span><span>ACCIONES</span></div>{loading&&<div className="noRows">Cargando…</div>}{!loading&&rows.map(x=><article key={x.id}><div className="pubInfo"><div className="pubFlags"><span>{x.date}</span>{x.promoted&&<b>OJO ACÁ{x.rank?` · #${x.rank}`:''}</b>}{x.rawStatus==='cancelled'&&<b>CANCELADA</b>}</div><h2>{x.title}</h2><p>{x.place} · {x.price}</p><small>Publicado {x.published}. Editar no cambia esta antigüedad.</small></div><div className="pubMetrics"><p><b>{x.views}</b><span>visitas</span></p><p><b>{x.clicks}</b><span>clicks afuera</span></p><p><b>{x.publisherViews}</b><span>traídas por vos</span></p></div><div className="pubActions"><Link href={`/che-mira-v5/p/${x.id}`}>Ver ↗</Link>{status!=='VENCIDAS'&&<Link href={`/che-mira-v5/publicar?edit=${encodeURIComponent(x.id)}`}>Editar</Link>}<button onClick={()=>share(x.id,x.title)}>Compartir</button><Link href={`/che-mira-v5/publicar?duplicate=${encodeURIComponent(x.id)}`}>{status==='VENCIDAS'?'Próxima fecha':'Repetir'}</Link>{status!=='VENCIDAS'&&<Link className="attention" href={`/che-mira-v5/ojo?listing=${encodeURIComponent(x.id)}`}>{x.promoted?(x.rank?`Ojo #${x.rank} · subir`:'Subir posición'):'Dar más atención'}</Link>}{status!=='VENCIDAS'&&<button className="cancel" onClick={()=>cancel(x.id,x.title)}>Cancelar</button>}</div></article>)}{!loading&&rows.length===0&&<div className="noRows">No hay publicaciones en este estado.</div>}</section></>}
    <section className="dashboardRule"><span>REGLA DEL FEED</span><h2>Podés corregir. No podés volver a nacer.</h2><p>Editar mantiene intacto el momento original de publicación. Si el evento se repite, “Próxima fecha” crea una publicación nueva y conserva la anterior como historial.</p></section></main>
}
