'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import './style.css';

type WindowRow={key:string;count:number;target:number;status:'red'|'yellow'|'green'};
type Invite={code:string;label:string|null;bonus_free_posts:number;max_uses:number;uses:number;active:boolean};
type Outreach={id:string;name:string;contact_email:string|null;contact_channel:string;source_url:string|null;invite_code:string|null;status:'new'|'contacted'|'replied'|'converted'|'closed';priority:number;notes:string|null};
type Data={windows:WindowRow[];neighborhoods:[string,number][];categories:[string,number][];funnel:Record<string,number>;invites:Invite[];outreach:Outreach[];communitySeed:number;total:number};
const neighborhoods=['Palermo','Chacarita','Villa Crespo','Almagro','Caballito','Colegiales','San Telmo','Recoleta','Núñez'];
const categories=['Comer','Música','Salir','Cultura','Experiencias'];
const statusLabel:Record<Outreach['status'],string>={new:'NUEVO',contacted:'CONTACTADO',replied:'RESPONDIÓ',converted:'CONVERTIDO',closed:'CERRADO'};

export default function AlphaOps(){
 const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState('');const [inviteLabel,setInviteLabel]=useState('Organizador alpha');const [bonus,setBonus]=useState(5);const [maxUses,setMaxUses]=useState(1);
 const [seed,setSeed]=useState({title:'',category:'Música',neighborhood:'Palermo',startsAt:'',venue:'',price:'',description:'',destination:'',destinationType:'web'});
 const token=()=>localStorage.getItem('cm_access_token')||'';
 const load=()=>fetch('/api/cm/admin/alpha',{headers:{Authorization:`Bearer ${token()}`}}).then(async r=>{if(r.status===401){window.location.href='/che-mira-v5/acceso?next=/che-mira-v5/admin/alpha';return null}if(!r.ok)throw new Error();return r.json()}).then(x=>{if(x?.data)setData(x.data)}).catch(()=>setMessage('No pudimos cargar operaciones alpha.'));
 useEffect(()=>{load()},[]);
 const createInvite=async(e:FormEvent)=>{e.preventDefault();setMessage('');const r=await fetch('/api/cm/admin/alpha',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({action:'create_invite',label:inviteLabel,bonus,maxUses})});const x=await r.json().catch(()=>({}));if(r.ok){setMessage(`Invitación ${x.data.code} creada.`);load()}else setMessage('No pudimos crear la invitación.')};
 const createSeed=async(e:FormEvent)=>{e.preventDefault();setMessage('');const r=await fetch('/api/cm/admin/alpha',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({action:'seed_listing',...seed})});const x=await r.json().catch(()=>({}));if(r.ok){setMessage(`Semilla publicada: ${x.data.title}`);setSeed(s=>({...s,title:'',venue:'',price:'',description:'',destination:''}));load()}else setMessage(x.error==='missing_fields'?'Faltan campos.':'No pudimos sembrar esa publicación.')};
 const setOutreach=async(id:string,status:Outreach['status'])=>{await fetch('/api/cm/admin/alpha',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({action:'outreach_status',id,status})});load()};
 const gap=data?.windows.reduce((n,x)=>n+Math.max(0,x.target-x.count),0)||0;
 return <main className="alphaOps"><header><Link href="/che-mira-v5/admin">← Backoffice</Link><span>ALPHA OPS</span><Link href="/che-mira-v5">Producto ↗</Link></header><section className="opsHero"><div><span>LIQUIDEZ · BUENOS AIRES</span><h1>¿Dónde falta<br/>movimiento?</h1></div><div className="heroStat"><b>{gap}</b><span>publicaciones faltan para objetivos mínimos</span></div></section>{message&&<div className="opsMessage">{message}</div>}{data&&<><section className="windowGrid">{data.windows.map(x=><article className={x.status} key={x.key}><span>{x.key}</span><b>{x.count}<small> / {x.target}</small></b><div><i style={{width:`${Math.min(100,x.count/x.target*100)}%`}}/></div><p>{x.status==='green'?'Hay masa crítica mínima.':x.status==='yellow'?'Cerca. Conviene sembrar.':`Faltan ${Math.max(0,x.target-x.count)} para que no se vea vacío.`}</p></article>)}</section><section className="opsColumns"><div className="densityCard"><div><span>DENSIDAD</span><b>{data.total} activas · {data.communitySeed} comunitarias</b></div><h3>Barrios</h3>{data.neighborhoods.map(([k,v])=><div className="barRow" key={k}><span>{k}</span><div><i style={{width:`${Math.min(100,v/Math.max(1,data.total)*250)}%`}}/></div><b>{v}</b></div>)}<h3>Categorías</h3>{data.categories.map(([k,v])=><div className="barRow" key={k}><span>{k}</span><div><i style={{width:`${Math.min(100,v/Math.max(1,data.total)*250)}%`}}/></div><b>{v}</b></div>)}</div><div className="funnelCard"><span>SEÑALES · 7D</span>{['home_view','explore_view','publish_start','publish_blocked','save','share','ojo_view','ojo_bid_attempt'].map(k=><div key={k}><b>{data.funnel[k]||0}</b><span>{k.replaceAll('_',' ')}</span></div>)}</div></section><section className="outreachCard"><div className="outreachHead"><div><span>CONVERTIR SUPPLY</span><h2>Que dejen de ser “nuestros” eventos.</h2></div><p>Prioridad: organizadores con agenda recurrente. Una conversión puede traer varias publicaciones por semana.</p></div><div className="outreachList">{data.outreach.map(x=><article key={x.id}><div><small>P{x.priority}</small><h3>{x.name}</h3><p>{x.notes}</p></div><div className="outreachMeta">{x.contact_email&&<a href={`mailto:${x.contact_email}`}>{x.contact_email}</a>}{x.source_url&&<a href={x.source_url} target="_blank" rel="noreferrer">Fuente ↗</a>}{x.invite_code&&<code>{x.invite_code}</code>}</div><div className="outreachStatus"><b className={`st-${x.status}`}>{statusLabel[x.status]}</b><select value={x.status} onChange={e=>setOutreach(x.id,e.target.value as Outreach['status'])}><option value="new">Nuevo</option><option value="contacted">Contactado</option><option value="replied">Respondió</option><option value="converted">Convertido</option><option value="closed">Cerrado</option></select></div></article>)}</div></section></>}
 <section className="opsForms"><form onSubmit={createInvite}><span>INVITAR ORGANIZADOR</span><h2>Dar runway, no plata.</h2><p>El bonus suma publicaciones gratis a la regla experimental del usuario.</p><label>Etiqueta<input value={inviteLabel} onChange={e=>setInviteLabel(e.target.value)}/></label><div className="two"><label>Bonus gratis<input type="number" min="1" max="20" value={bonus} onChange={e=>setBonus(Number(e.target.value))}/></label><label>Usos<input type="number" min="1" max="100" value={maxUses} onChange={e=>setMaxUses(Number(e.target.value))}/></label></div><button>Crear invitación →</button>{data?.invites?.length?<div className="inviteList">{data.invites.slice(0,6).map(x=><div key={x.code}><code>{x.code}</code><span>{x.uses}/{x.max_uses} usos · +{x.bonus_free_posts} posts</span><button type="button" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/che-mira-v5/alpha?code=${x.code}`)}>Copiar link</button></div>)}</div>:null}</form>
 <form onSubmit={createSeed}><span>SEMBRAR OFERTA</span><h2>Carga comunitaria rápida.</h2><p>Queda sin reclamar y el dueño puede reclamarla después.</p><label>Título<input value={seed.title} onChange={e=>setSeed({...seed,title:e.target.value})}/></label><div className="two"><label>Categoría<select value={seed.category} onChange={e=>setSeed({...seed,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Barrio<select value={seed.neighborhood} onChange={e=>setSeed({...seed,neighborhood:e.target.value})}>{neighborhoods.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Fecha y hora<input type="datetime-local" value={seed.startsAt} onChange={e=>setSeed({...seed,startsAt:e.target.value})}/></label><label>Lugar<input value={seed.venue} onChange={e=>setSeed({...seed,venue:e.target.value})}/></label><div className="two"><label>Precio<input value={seed.price} onChange={e=>setSeed({...seed,price:e.target.value})}/></label><label>Destino<select value={seed.destinationType} onChange={e=>setSeed({...seed,destinationType:e.target.value})}><option value="web">Web</option><option value="instagram">Instagram</option><option value="whatsapp">WhatsApp</option><option value="checkout">Checkout</option></select></label></div><label>Link<input type="url" value={seed.destination} onChange={e=>setSeed({...seed,destination:e.target.value})}/></label><label>Descripción<textarea value={seed.description} onChange={e=>setSeed({...seed,description:e.target.value})}/></label><button>Publicar semilla →</button></form></section></main>
}
