import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {eventLabel,ctaLabel,isCheToday} from '../../lib';
import DetailActions from './actions';
import '../../style.css';
import './style.css';

type Listing={slug:string;title:string;category:string;neighborhood:string;venue:string|null;starts_at:string;price_label:string|null;description:string|null;destination_type:string;claimed:boolean;source_type:string;status:string};
const SUPABASE_URL=process.env.SUPABASE_URL||'https://wpherlcpgktqpyfcrqxs.supabase.co';
const KEY=process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_twh0JhBP7h5c7XQi_TsgCw_-BFEGQqS';
async function getListing(slug:string):Promise<Listing|null>{const p=new URLSearchParams({select:'slug,title,category,neighborhood,venue,starts_at,price_label,description,destination_type,claimed,source_type,status',slug:`eq.${slug}`,limit:'1'});const r=await fetch(`${SUPABASE_URL}/rest/v1/cm_listings?${p}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)return null;const rows=await r.json();return rows[0]||null}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params,item=await getListing(id);if(!item||!isCheToday(item.starts_at))return{title:'CHE, MIRÁ — Hoy en Buenos Aires',description:'Lo que está tratando de llamar tu atención hoy.'};const description=`${eventLabel(item.starts_at)} · ${item.neighborhood}${item.price_label?` · ${item.price_label}`:''}`;return{title:`${item.title} — CHE, MIRÁ`,description,openGraph:{title:item.title,description,type:'article',locale:'es_AR'},twitter:{card:'summary_large_image',title:item.title,description}}}
export default async function DetailV6({params}:{params:Promise<{id:string}>}){const{id}=await params,item=await getListing(id);if(!item||!isCheToday(item.starts_at))notFound();const claimed=item.claimed?'RECLAMADA':item.source_type==='community'?'SIN RECLAMAR':'ORGANIZADOR';return <main className="cm6 detail6"><header className="cm6Top"><Link href="/che-mira-v6" className="cm6Logo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v6/explorar">Explorar hoy</Link><Link href="/che-mira-v5/guardados">Mis planes</Link><Link href="/che-mira-v6/publicar" className="cm6Publish">+ Publicar</Link></nav></header><section className="detail6Layout"><article><div className="detail6Meta"><span>{eventLabel(item.starts_at)}</span><b>{item.category}</b></div><h1>{item.title}</h1>{item.description&&<p className="detail6Lead">{item.description}</p>}<div className="detail6Facts"><div><small>DÓNDE</small><strong>{item.neighborhood}</strong>{item.venue&&<span>{item.venue}</span>}</div><div><small>PRECIO</small><strong>{item.price_label||'Consultar'}</strong></div></div><a className="detail6Primary" href={`/api/cm/go?slug=${encodeURIComponent(item.slug)}`} target="_blank" rel="noreferrer">{ctaLabel(item.destination_type)}</a><DetailActions slug={item.slug} title={item.title} startsAt={item.starts_at} venue={item.venue||''} neighborhood={item.neighborhood}/></article><aside><span>PUBLICACIÓN DE HOY</span><b>{claimed}</b><p>CHE, MIRÁ no recomienda. Si una publicación pone plata, sube en el ranking. Si no, manda la recencia.</p>{!item.claimed&&<Link href={`/che-mira-v5/reclamar?listing=${encodeURIComponent(item.slug)}`}>¿Esto es tuyo? Reclamar →</Link>}<Link href={`/che-mira-v5/reportar?listing=${encodeURIComponent(item.slug)}`}>Reportar</Link></aside></section><section className="detail6More"><span>YA QUE ESTÁS ACÁ</span><h2>¿Qué más quiere que mires hoy?</h2><div><Link href="/che-mira-v6">Volver al ranking →</Link><Link href="/che-mira-v6/explorar">Explorar hoy →</Link></div></section></main>}
