'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {CityPulse,CountryPulse,DbCity,DbLeaderboardEntry,DbLiveMarket,DbLiveMarketPlace,DbPlace,DbSeason,fetchCities,fetchCityBundle,fetchWorldPulse,submitPlace} from '../lib/supabase-public';

type Category='All'|'Eat'|'Drink'|'Do'|'See'|'Stay'|'Shop'|'Night'|'Useful';
const categories:Category[]=['All','Eat','Drink','Do','See','Stay','Shop','Night','Useful'];
const fallbackImage='https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80';
function labelCategory(c:DbPlace['category']){return(c[0].toUpperCase()+c.slice(1)) as Exclude<Category,'All'>}
function priceTier(n:number|null){return n?'$'.repeat(n):'—'}
function money(c:number){return c%100===0?`$${c/100}`:`$${(c/100).toFixed(2)}`}
function timeLeft(endsAt:string|null,now:number){if(!endsAt)return'';const ms=new Date(endsAt).getTime()-now;if(ms<=0)return'ended';const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return h>=24?`${Math.floor(h/24)}d ${h%24}h left`:`${h}h ${m}m left`}

export default function Home(){
 const[cities,setCities]=useState<DbCity[]>([]);const[cityName,setCityName]=useState('Buenos Aires');const[city,setCity]=useState<DbCity|null>(null);const[places,setPlaces]=useState<DbPlace[]>([]);
 const[season,setSeason]=useState<DbSeason|null>(null);const[leaderboard,setLeaderboard]=useState<DbLeaderboardEntry[]>([]);const[markets,setMarkets]=useState<DbLiveMarket[]>([]);const[marketPlaces,setMarketPlaces]=useState<DbLiveMarketPlace[]>([]);const[marketSeasons,setMarketSeasons]=useState<DbSeason[]>([]);const[marketBoards,setMarketBoards]=useState<Record<string,DbLeaderboardEntry[]>>({});const[activeMarketId,setActiveMarketId]=useState<string|null>(null);
 const[cityPulse,setCityPulse]=useState<CityPulse[]>([]);const[countryPulse,setCountryPulse]=useState<CountryPulse[]>([]);const[category,setCategory]=useState<Category>('All');const[query,setQuery]=useState('');const[modal,setModal]=useState<'bid'|'add'|'claim'|null>(null);const[loading,setLoading]=useState(true);const[submitStatus,setSubmitStatus]=useState('');const[now,setNow]=useState(Date.now());
 useEffect(()=>{fetchCities().then(setCities).catch(console.error);fetchWorldPulse().then(p=>{setCityPulse(p.cities);setCountryPulse(p.countries)}).catch(console.error)},[]);
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t)},[]);
 useEffect(()=>{let live=true;setLoading(true);fetchCityBundle(cityName).then(b=>{if(!live)return;if(!b){setCity(null);setPlaces([]);setMarkets([]);setMarketPlaces([]);setMarketSeasons([]);setMarketBoards({});setSeason(null);setLeaderboard([])}else{setCity(b.city);setPlaces(b.places);setMarkets(b.markets);setMarketPlaces(b.marketPlaces);setMarketSeasons(b.marketSeasons);setMarketBoards(b.marketBoards);setSeason(b.season);setLeaderboard(b.leaderboard);setActiveMarketId(prev=>b.markets.some(m=>m.id===prev)?prev:(b.markets[0]?.id??null))}setLoading(false)}).catch(()=>setLoading(false));return()=>{live=false}},[cityName]);
 const displayCity=city?.name??cityName,displayCountry=city?.country_name??'Local guide',tagline=city?.hero_copy??'This city is waiting for locals to build it.';
 const activeMarket=markets.find(m=>m.id===activeMarketId)??null;const activeMemberships=activeMarket?marketPlaces.filter(mp=>mp.market_id===activeMarket.id):[];const activeMarketPlaceIds=new Set(activeMemberships.map(mp=>mp.place_id));const activeMarketCatalog=places.filter(p=>activeMarketPlaceIds.has(p.id));const marketSeason=activeMarket?marketSeasons.find(s=>s.market_id===activeMarket.id):null;const marketBoard=activeMarket?marketBoards[activeMarket.id]??[]:[];const marketLeader=marketBoard[0]??null;const marketTake=(marketLeader?.total_cents??0)+(marketSeason?.min_increment_cents??100);
 const visible=useMemo(()=>category==='All'?places:places.filter(p=>labelCategory(p.category)===category),[category,places]);const leader=leaderboard[0]??null;const crownPlace=leader?places.find(p=>p.id===leader.place_id):null;const cityTake=(leader?.total_cents??0)+(season?.min_increment_cents??100);
 function search(e:FormEvent){e.preventDefault();const clean=query.trim();if(!clean)return;const match=cities.find(c=>c.name.toLowerCase()===clean.toLowerCase());setCityName(match?.name??clean);setCategory('All')}
 function choose(n:string){setCityName(n);setCategory('All');window.scrollTo({top:420,behavior:'smooth'})}
 async function addPlace(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitStatus('Saving…');const fd=new FormData(e.currentTarget);try{await submitPlace({city_name:displayCity,country_name:city?.country_name,place_name:String(fd.get('place_name')||''),category:String(fd.get('category')||'eat') as DbPlace['category'],website_url:String(fd.get('website_url')||'')||undefined,instagram_url:String(fd.get('instagram_url')||'')||undefined,note:String(fd.get('note')||'')||undefined,submitter_email:String(fd.get('email')||'')||undefined});setSubmitStatus('Submitted. It is now in the moderation queue.');e.currentTarget.reset()}catch{setSubmitStatus('Could not submit. Try again.')}}
 return <main>
  <header className="nav shell"><div className="brand">COME<span>VISIT</span></div><div className="navright"><span className="live">● LIVE CITY</span><button onClick={()=>setModal('claim')}>For local businesses</button></div></header>
  <section className="hero shell"><div className="kicker">THE WORLD, BUILT BY LOCALS</div><h1>Land somewhere.<br/><em>Know what to do.</em></h1><p>See what is worth doing now, tonight and this weekend — then let local businesses compete transparently for attention.</p><form onSubmit={search} className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Where are you going?"/><button>Explore</button></form><small>v4 preview · Buenos Aires is the launch laboratory · demo inventory is labeled.</small></section>
  <section className="cityswitch shell"><div><span className="eyebrow">LIVE CITIES</span><h2>Pick a city</h2></div><div className="citybuttons">{cities.map(c=><button key={c.id} className={c.name===cityName?'active':''} onClick={()=>choose(c.name)}>{c.name}</button>)}</div></section>
  <section className="cityhero shell"><div><span className="country">{displayCountry}</span><h2>{displayCity}</h2><p>{tagline}</p></div><div className="stats"><span><b>{markets.length}</b> live contexts</span><span><b>{places.length}</b> loaded places</span><small>{city?'Live database · demo launch data':'No catalog yet'}</small></div></section>

  {markets.length>0?<><section className="shell model"><div><span className="eyebrow">LIVE CITY · WHAT MATTERS NOW</span><h2>{activeMarket?.title}</h2><p>{activeMarket?.description}</p><div className="citybuttons" style={{marginTop:18}}>{markets.map(m=><button key={m.id} className={m.id===activeMarketId?'active':''} onClick={()=>setActiveMarketId(m.id)}>{m.title}</button>)}</div></div><div className="board">{marketBoard.slice(0,3).map(e=><div className={e.rank===1?'row winner':'row'} key={e.place_id}><b>#{e.rank}</b><span><strong>{e.place_name}</strong><small>{e.bid_count} move{e.bid_count===1?'':'s'} · {activeMarket?.eyebrow??'LIVE'}</small></span><em>{money(e.total_cents)}</em></div>)}{marketBoard.length===0?<div className="row winner"><b>●</b><span><strong>{activeMarket?.place_count??0} places live</strong><small>No business is competing for this context yet.</small></span><em>open</em></div>:null}<button onClick={()=>setModal('bid')}>{marketBoard.length?`Take #1 at ${money(marketTake)}`:'Open the market'} ↗</button></div></section>
  <section className="shell grid">{activeMarketCatalog.map(p=>{const note=activeMemberships.find(mp=>mp.place_id===p.id)?.editorial_note;const rank=marketBoard.find(e=>e.place_id===p.id)?.rank;return <article key={p.id} className={rank===1?'card paid':'card'}><div className="photo" style={{backgroundImage:`url(${p.image_url||fallbackImage})`}}>{rank===1?<><span className="badge">{activeMarket?.eyebrow??'LIVE'} CROWN</span><span className="paidtag">Sponsored · {money(marketLeader?.total_cents??0)}</span></>:<span className="badge">{note??'LIVE PICK'}</span>}</div><div className="body"><div className="meta"><span>{labelCategory(p.category)}</span><span>{priceTier(p.price_tier)}</span></div><h3>{p.name}</h3><p>{p.short_description||'Local recommendation.'}</p><div className="bottom"><span>⌖ {p.neighborhood||displayCity}</span><button>Open ↗</button></div></div></article>})}</section></>:null}

  <section className="shell strip"><div><span className="eyebrow">BUILD THE CITY</span><h2>Know a place that belongs here?</h2><p>Add it free. If you own a business, claim and verify it free. Paying only starts when you choose to compete for attention.</p></div><div><button className="ghost" onClick={()=>setModal('add')}>+ Add a place</button><button onClick={()=>setModal('claim')}>Claim your business · free</button></div></section>

  <section className="shell crown"><div><div className="eyebrow">♛ WEEKLY CITY CROWN · SPONSORED</div><h3>{crownPlace?.name??'No one'} {crownPlace?'leads':'has claimed'} {displayCity} this week.</h3><p>The broad city market stays alive underneath contextual markets like Tonight and This weekend.</p><div className="crowndata"><span>{leader?`${money(leader.total_cents)} leader total`:'Crown open'}</span><span>{season?timeLeft(season.ends_at,now):'No active season'}</span><span>{season?.is_demo?'Demo market':'Live market'}</span></div></div><button className="take" onClick={()=>setModal('bid')}><small>TAKE CITY CROWN</small><b>{money(cityTake)}</b><span>↗</span></button></section>

  <section className="shell filters">{categories.map(c=><button key={c} className={c===category?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</section>
  {loading?<section className="shell empty"><h3>Loading {displayCity}…</h3></section>:places.length===0?<section className="shell empty"><h3>Be one of the first locals to build {displayCity}.</h3><button onClick={()=>setModal('add')}>+ Add the first place</button></section>:<section className="shell grid">{visible.map(p=><article key={p.id} className={crownPlace?.id===p.id?'card paid':'card'}><div className="photo" style={{backgroundImage:`url(${p.image_url||fallbackImage})`}}>{p.is_demo?<span className="badge">DEMO PLACE</span>:null}</div><div className="body"><div className="meta"><span>{labelCategory(p.category)}</span><span>{priceTier(p.price_tier)}</span></div><h3>{p.name}</h3><p>{p.short_description||'Local recommendation.'}</p><div className="bottom"><span>⌖ {p.neighborhood||displayCity}</span><button>Open ↗</button></div></div></article>)}</section>}

  <section className="shell model"><div><span className="eyebrow">WORLD PULSE</span><h2>The world is being built.<br/>Watch where it moves.</h2><p>Community and competitive activity become public city and country signals.</p></div><div className="board">{countryPulse.slice(0,3).map((c,i)=><div className={i===0?'row winner':'row'} key={c.country_code}><b>#{i+1}</b><span><strong>{c.country_name}</strong><small>{c.active_cities} cities · {c.published_places} real places</small></span><em>{money(c.crown_volume_cents)}</em></div>)}</div></section>
  <section className="shell model"><div><span className="eyebrow">MOST COMPETITIVE CITIES</span><h2>City versus city.</h2><p>Competition is one leaderboard; Most Built, Fastest Growing and Most Active come next.</p></div><div className="board">{cityPulse.slice(0,5).map((c,i)=><div className={i===0?'row winner':'row'} key={c.city_id}><b>#{i+1}</b><span><strong>{c.city_name}</strong><small>{c.country_name} · {c.crown_bid_events} moves</small></span><em>{money(c.crown_volume_cents)}</em></div>)}</div></section>
  <footer className="shell footer"><div className="brand">COME<span>VISIT</span></div><p>The world, built by locals.</p><span>v0.4 · Live City</span></footer>

  {modal?<div className="overlay" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(null)}>×</button><span className="eyebrow">{modal==='bid'?'ATTENTION MARKET':modal==='claim'?'BUSINESS OWNERS':'LOCALS'}</span><h2>{modal==='bid'?(activeMarket?`Compete in ${activeMarket.title}`:`Take the ${displayCity} Crown`):modal==='claim'?'Find and verify your business — free':`Add a place to ${displayCity}`}</h2>{modal==='add'?<form onSubmit={addPlace} style={{display:'grid',gap:12}}><input required name="place_name" placeholder="Place name"/><select name="category" defaultValue="eat"><option>eat</option><option>drink</option><option>do</option><option>see</option><option>stay</option><option>shop</option><option>night</option><option>useful</option></select><input name="website_url" placeholder="Website (optional)"/><input name="instagram_url" placeholder="Instagram (optional)"/><input name="email" type="email" placeholder="Your email (optional)"/><textarea name="note" placeholder="Why should travelers know it?"/><button type="submit">Submit place</button>{submitStatus?<small>{submitStatus}</small>:null}</form>:modal==='claim'?<><p>Next implementation block: search the business through Google identity, authenticate the owner, verify control, then create or link the ComeVisit place.</p><button onClick={()=>setModal(null)}>Continue soon</button></>:<><p>The market engine is real; checkout is still disabled. Verified businesses will fund a ComeVisit balance and only pay the difference needed to overtake the current leader.</p><p><strong>{activeMarket?.title??`${displayCity} City Crown`}:</strong> current take price {activeMarket?money(marketTake):money(cityTake)}.</p><button onClick={()=>setModal(null)}>Got it</button></>}</div></div>:null}
 </main>
}
