'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import './style.css';

type Listing={slug:string;title:string;neighborhood:string;venue:string|null;claimed:boolean};
export default function Reclamar(){
  const [slug,setSlug]=useState('');const [listing,setListing]=useState<Listing|null>(null);const [note,setNote]=useState('');const [status,setStatus]=useState<'idle'|'sending'|'done'>('idle');const [error,setError]=useState('');
  useEffect(()=>{const q=new URLSearchParams(window.location.search);const s=q.get('listing')||'';setSlug(s);if(s)fetch(`/api/cm/listings?slug=${encodeURIComponent(s)}`).then(r=>r.json()).then(x=>setListing(x.data)).catch(()=>{})},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();const token=localStorage.getItem('cm_access_token');if(!token){window.location.href=`/che-mira-v5/acceso?next=${encodeURIComponent(`/che-mira-v5/reclamar?listing=${slug}`)}`;return}setStatus('sending');setError('');const r=await fetch('/api/cm/claim',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({slug,note})});const data=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem('cm_access_token');window.location.href=`/che-mira-v5/acceso?next=${encodeURIComponent(`/che-mira-v5/reclamar?listing=${slug}`)}`;return}if(!r.ok){setStatus('idle');setError(data.error==='already_claimed'?'Esta publicación ya fue reclamada.':'No pudimos enviar el reclamo.');return}setStatus('done')};
  return <main className="controlPage"><header className="controlTop"><Link href="/che-mira-v5" className="controlLogo">CHE, MIRÁ</Link><span>RECLAMAR</span><Link href={slug?`/che-mira-v5/p/${slug}`:'/che-mira-v5'}>Cerrar</Link></header><section className="controlLayout"><div className="controlCopy"><span>CONTROL DE LA PUBLICACIÓN</span><h1>¿Es tuyo?</h1><p>Reclamar no cambia la posición ni la antigüedad. Sólo verifica quién puede editar y promocionar esta publicación.</p>{listing&&<div className="subject"><small>PUBLICACIÓN</small><strong>{listing.title}</strong><span>{listing.neighborhood}{listing.venue?` · ${listing.venue}`:''}</span></div>}</div><form onSubmit={submit} className="controlCard"><span>CONTANOS CÓMO LO VERIFICAMOS</span><div className="proofOptions"><button type="button">Instagram oficial</button><button type="button">Web / dominio</button><button type="button">Email del negocio</button><button type="button">Otro</button></div><label><b>Prueba o contexto</b><textarea value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="Ej. Soy administrador de @cuentaoficial / mi email pertenece al dominio del lugar."/></label>{error&&<p className="controlError">{error}</p>}{status==='done'?<div className="controlDone"><b>Reclamo enviado.</b><span>Queda pendiente de verificación.</span></div>:<button className="controlSubmit" disabled={!slug||status==='sending'}>{status==='sending'?'Enviando…':'Enviar reclamo →'}</button>}<small>Si todavía no iniciaste sesión, te vamos a pedir una cuenta antes de enviar.</small></form></section></main>
}
