'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import './style.css';

type Listing={slug:string;title:string;neighborhood:string;venue:string|null;claimed:boolean;category?:string;starts_at?:string;destination_url?:string};
const when=(iso?:string)=>iso?new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)).replace(',',' ·').toUpperCase():'';

export default function Reclamar(){
  const [slug,setSlug]=useState('');const [listing,setListing]=useState<Listing|null>(null);const [note,setNote]=useState('');const [status,setStatus]=useState<'idle'|'sending'|'done'>('idle');const [error,setError]=useState('');
  const [bulk,setBulk]=useState<Listing[]>([]);const [selected,setSelected]=useState<string[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [auth,setAuth]=useState(true);const [bulkMessage,setBulkMessage]=useState('');
  const token=()=>localStorage.getItem('cm_access_token')||'';
  const loadBulk=async(term='')=>{const t=token();if(!t){setAuth(false);setLoading(false);return}setLoading(true);const r=await fetch(`/api/cm/claim/candidates?q=${encodeURIComponent(term)}`,{headers:{Authorization:`Bearer ${t}`}});if(r.status===401){setAuth(false);setLoading(false);return}const x=await r.json().catch(()=>({}));setBulk(x.data||[]);setLoading(false)};
  useEffect(()=>{const p=new URLSearchParams(window.location.search);const s=p.get('listing')||'';setSlug(s);if(s){fetch(`/api/cm/listings?slug=${encodeURIComponent(s)}`).then(r=>r.json()).then(x=>setListing(x.data)).catch(()=>{});setLoading(false)}else loadBulk('')},[]);
  useEffect(()=>{if(slug)return;const id=setTimeout(()=>loadBulk(q),250);return()=>clearTimeout(id)},[q,slug]);
  const submit=async(e:FormEvent)=>{e.preventDefault();const t=token();if(!t){window.location.href=`/che-mira-v5/acceso?next=${encodeURIComponent(`/che-mira-v5/reclamar?listing=${slug}`)}`;return}setStatus('sending');setError('');const r=await fetch('/api/cm/claim',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({slug,note})});const data=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem('cm_access_token');window.location.href=`/che-mira-v5/acceso?next=${encodeURIComponent(`/che-mira-v5/reclamar?listing=${slug}`)}`;return}if(!r.ok){setStatus('idle');setError(data.error==='already_claimed'?'Esta publicación ya fue reclamada.':'No pudimos enviar el reclamo.');return}setStatus('done')};
  const toggle=(s:string)=>setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
  const submitBulk=async()=>{if(!selected.length)return;const t=token();if(!t){setAuth(false);return}setBulkMessage('');const r=await fetch('/api/cm/claim/candidates',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({slugs:selected,note:'Soy el organizador o representante de estas publicaciones.'})});const x=await r.json().catch(()=>({}));if(r.ok){setBulkMessage(`${x.created||0} reclamos enviados. Los revisamos antes de transferir el control.`);setSelected([]);loadBulk(q)}else setBulkMessage('No pudimos enviar los reclamos.')};
  const visible=useMemo(()=>bulk,[bulk]);

  if(slug)return <main className="controlPage"><header className="controlTop"><Link href="/che-mira-v5" className="controlLogo">CHE, MIRÁ</Link><span>RECLAMAR</span><Link href={`/che-mira-v5/p/${slug}`}>Cerrar</Link></header><section className="controlLayout"><div className="controlCopy"><span>CONTROL DE LA PUBLICACIÓN</span><h1>¿Es tuyo?</h1><p>Reclamar no cambia la posición ni la antigüedad. Sólo verifica quién puede editar y promocionar esta publicación.</p>{listing&&<div className="subject"><small>PUBLICACIÓN</small><strong>{listing.title}</strong><span>{listing.neighborhood}{listing.venue?` · ${listing.venue}`:''}</span></div>}<Link className="claimAllLink" href="/che-mira-v5/reclamar">¿Tenés varias fechas cargadas? Reclamar varias →</Link></div><form onSubmit={submit} className="controlCard"><span>CONTANOS CÓMO LO VERIFICAMOS</span><div className="proofOptions"><button type="button">Instagram oficial</button><button type="button">Web / dominio</button><button type="button">Email del negocio</button><button type="button">Otro</button></div><label><b>Prueba o contexto</b><textarea value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="Ej. Soy administrador de @cuentaoficial / mi email pertenece al dominio del lugar."/></label>{error&&<p className="controlError">{error}</p>}{status==='done'?<div className="controlDone"><b>Reclamo enviado.</b><span>Queda pendiente de verificación.</span></div>:<button className="controlSubmit" disabled={!slug||status==='sending'}>{status==='sending'?'Enviando…':'Enviar reclamo →'}</button>}<small>Si todavía no iniciaste sesión, te vamos a pedir una cuenta antes de enviar.</small></form></section></main>;

  if(!auth)return <main className="controlPage"><header className="controlTop"><Link href="/che-mira-v5" className="controlLogo">CHE, MIRÁ</Link><span>RECLAMAR</span></header><section className="claimGate"><h1>Primero entrá.</h1><p>Necesitamos saber a qué cuenta transferir las publicaciones.</p><Link href="/che-mira-v5/acceso?next=/che-mira-v5/reclamar">Entrar →</Link></section></main>;

  return <main className="controlPage"><header className="controlTop"><Link href="/che-mira-v5" className="controlLogo">CHE, MIRÁ</Link><span>CLAIM ASISTIDO</span><Link href="/che-mira-v5/mis-publicaciones">Mis publicaciones ↗</Link></header><section className="bulkHero"><div><span>RECLAMAR EN LOTE</span><h1>Encontrá todo<br/>lo que ya es tuyo.</h1></div><p>Si la comunidad cargó varias fechas tuyas, no las reclames una por una. Buscá por nombre, lugar o link original y mandanos el lote.</p></section><section className="bulkSearch"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ej: Sabe la Tierra, Usina, teatro, instagram.com/..."/><b>{selected.length} seleccionadas</b></section>{bulkMessage&&<div className="bulkMessage">{bulkMessage}</div>}<section className="candidateList">{loading&&<div className="claimEmpty">Buscando…</div>}{!loading&&visible.map(x=><article key={x.slug} className={selected.includes(x.slug)?'selected':''} onClick={()=>toggle(x.slug)}><div className="check">{selected.includes(x.slug)?'✓':''}</div><div><small>{when(x.starts_at)}{x.category?` · ${x.category}`:''}</small><h2>{x.title}</h2><p>{x.neighborhood}{x.venue?` · ${x.venue}`:''}</p>{x.destination_url&&<a href={x.destination_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Ver fuente ↗</a>}</div></article>)}{!loading&&!visible.length&&<div className="claimEmpty">No encontramos publicaciones sin reclamar con esa búsqueda.</div>}</section><div className="claimBar"><div><b>{selected.length}</b><span>publicaciones para reclamar</span></div><button disabled={!selected.length} onClick={submitBulk}>Enviar reclamo de lote →</button></div></main>
}
