'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {WINDOWS,WindowKey,eligible,eventLabel} from '../lib';
import '../style.css';
import './style.css';

type Listing={slug:string;title:string;category:string;neighborhood:string;venue:string|null;starts_at:string;price_label:string|null;description:string|null;latitude:number|null;longitude:number|null};
const categories=['TODO','COMER','MÚSICA','SALIR','CULTURA','EXPERIENCIAS'];
const priceTier=(label:string|null)=>{if(!label||/gratis/i.test(label))return'GRATIS';const n=Number((label.match(/[\d.]+/)?.[0]||'0').replace(/\./g,''));return n>=45000?'$$$':n>=18000?'$$':'$'};

export default function Explorar(){
 const[items,setItems]=useState<Listing[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const[when,setWhen]=useState<WindowKey>('HOY');const[category,setCategory]=useState('TODO');const[hood,setHood]=useState('TODOS');const[price,setPrice]=useState('TODOS');const[q,setQ]=useState('');const[near,setNear]=useState(false);const[coords,setCoords]=useState<[number,number]|null>(null);
 useEffect(()=>{const s=new URLSearchParams(location.search),w=s.get('cuando') as WindowKey|null;if(w&&WINDOWS.includes(w))setWhen(w);fetch('/api/cm/listings').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>setItems(Array.isArray(x.data)?x.data:[])).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);
 const hoods=useMemo(()=>['TODOS',...Array.from(new Set(items.map(x=>x.neighborhood))).sort()],[items]);
 const distance=(x:Listing)=>{if(!coords||x.latitude==null||x.longitude==null)return Infinity;const[a,b]=coords,[c,d]=[x.latitude,x.longitude],R=6371,rad=(v:number)=>v*Math.PI/180;const da=rad(c-a),db=rad(d-b),s=Math.sin(da/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(s))};
 const results=useMemo(()=>items.filter(x=>eligible(x.starts_at,when)&&(category==='TODO'||x.category===category)&&(hood==='TODOS'||x.neighborhood===hood)&&(price==='TODOS'||priceTier(x.price_label)===price)&&(!q||`${x.title} ${x.neighborhood} ${x.venue||''} ${x.description||''}`.toLowerCase().includes(q.toLowerCase()))&&(!near||distance(x)<=3)).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime()),[items,when,category,hood,price,q,near,coords]);
 const enableNear=()=>{if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{setCoords([p.coords.latitude,p.coords.longitude]);setNear(true)})};
 return <main className="cm6 explore6"><header className="cm6Top"><Link href="/che-mira-v6" className="cm6Logo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v6">Inicio</Link><Link href="/che-mira-v5/guardados">Mis planes</Link><Link href="/che-mira-v6/publicar" className="cm6Publish">+ Publicar</Link></nav></header><section className="explore6Hero"><span>EXPLORAR · SIN RECOMENDACIÓN</span><h1>Encontrá algo.</h1><p>Vos elegís los filtros. Nosotros sólo ordenamos por horario.</p></section><section className="explore6Filters"><div className="explore6Search"><label>BUSCAR</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Jazz, pasta, San Telmo…"/></div><div><label>CUÁNDO</label><div className="miniChips">{WINDOWS.map(x=><button key={x} className={when===x?'active':''} onClick={()=>setWhen(x)}>{x}</button>)}</div></div><div><label>QUÉ</label><div className="miniChips">{categories.map(x=><button key={x} className={category===x?'active':''} onClick={()=>setCategory(x)}>{x}</button>)}</div></div><div className="selectPair"><label>DÓNDE<select value={hood} onChange={e=>setHood(e.target.value)}>{hoods.map(x=><option key={x}>{x}</option>)}</select></label><label>PRECIO<select value={price} onChange={e=>setPrice(e.target.value)}>{['TODOS','GRATIS','$','$$','$$$'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className={near?'near active':'near'} onClick={near?()=>setNear(false):enableNear}>{near?'✓ A menos de 3 km':'◎ Cerca mío'}</button></section><section className="explore6Results"><div className="explore6Meta"><b>{results.length} RESULTADOS</b><span>{when} · horario real, de menor a mayor</span></div>{loading&&<div className="cm6State">Cargando oferta…</div>}{error&&<div className="cm6State error">No pudimos cargar la oferta.</div>}{!loading&&!error&&results.map(x=><article key={x.slug}><div><strong>{eventLabel(x.starts_at)}</strong><small>{x.category}</small></div><div><h2><Link href={`/che-mira-v6/p/${x.slug}`}>{x.title}</Link></h2><p>{x.neighborhood}{x.venue?` · ${x.venue}`:''}{x.description?` · ${x.description}`:''}</p></div><div className="resultEnd"><strong>{x.price_label||'Consultar'}</strong>{coords&&distance(x)!==Infinity&&<small>{distance(x).toFixed(1)} km</small>}<Link href={`/che-mira-v6/p/${x.slug}`}>Ver →</Link></div></article>)}{!loading&&!error&&!results.length&&<div className="cm6State">No hay resultados con estos filtros. Probá ampliar la búsqueda.</div>}</section></main>
}
