'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import './style.css';

type Entry={id:number;delta_minor:number;balance_after_minor:number;kind:string;created_at:string;metadata?:Record<string,unknown>};
type Topup={id:string;amount_minor:number;status:string;created_at:string;init_point:string|null};
type WalletData={account:{currency:string;balance_minor:number};entries:Entry[];topups:Topup[];paymentsConfigured:boolean};
const money=(n:number)=>'$'+new Intl.NumberFormat('es-AR').format(n);
const date=(iso:string)=>new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));

export default function Wallet(){
  const [data,setData]=useState<WalletData|null>(null);const [amount,setAmount]=useState(25000);const [loading,setLoading]=useState(true);const [paying,setPaying]=useState(false);const [message,setMessage]=useState('');const [needsAuth,setNeedsAuth]=useState(false);
  const load=()=>{const token=localStorage.getItem('cm_access_token');if(!token){setNeedsAuth(true);setLoading(false);return}fetch('/api/cm/wallet',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(r.status===401){setNeedsAuth(true);return null}return r.ok?r.json():Promise.reject()}).then(x=>{if(x?.data)setData(x.data)}).catch(()=>setMessage('No pudimos cargar el saldo.')).finally(()=>setLoading(false))};
  useEffect(()=>{load();const q=new URLSearchParams(window.location.search);const p=q.get('payment');if(p==='success')setMessage('Mercado Pago aprobó el pago. El saldo se acredita cuando llega la confirmación segura.');if(p==='pending')setMessage('El pago quedó pendiente. El saldo aparecerá cuando Mercado Pago lo apruebe.');if(p==='failure')setMessage('El pago no se completó.')},[]);
  const topup=async(e:FormEvent)=>{e.preventDefault();const token=localStorage.getItem('cm_access_token');if(!token)return;setPaying(true);setMessage('');const r=await fetch('/api/cm/wallet/topup',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({amount})});const x=await r.json().catch(()=>({}));setPaying(false);if(!r.ok){if(x?.error==='payments_not_configured')setMessage('La integración de Mercado Pago está construida. Faltan cargar las credenciales privadas en Vercel para habilitar pagos.');else setMessage('No pudimos abrir Mercado Pago.');return}window.location.href=x.data.checkoutUrl};
  if(needsAuth)return <main className="walletPage"><header className="walletTop"><Link href="/che-mira-v5">CHE, MIRÁ</Link></header><section className="walletEmpty"><h1>Entrá para ver tu saldo.</h1><Link href="/che-mira-v5/acceso?next=/che-mira-v5/wallet">Entrar →</Link></section></main>;
  return <main className="walletPage"><header className="walletTop"><Link href="/che-mira-v5" className="walletLogo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v5/ojo">Ojo Acá</Link><Link href="/che-mira-v5/mis-publicaciones">Mis publicaciones</Link></nav></header><section className="walletHero"><div><span>SALDO PARA OJO ACÁ</span><h1>{loading?'—':money(data?.account.balance_minor||0)}</h1><p>El saldo se usa para subir posiciones. Cada aumento descuenta sólo la diferencia.</p></div><div className="walletRule"><b>Ejemplo</b><p>Estás en $12.000 y subís a $18.000 → se descuentan $6.000.</p><small>No podés bajar una puja para recuperar saldo ya gastado.</small></div></section>{message&&<div className="walletMessage">{message}</div>}<div className="walletGrid"><form className="topupCard" onSubmit={topup}><span>CARGAR SALDO</span><h2>Mercado Pago</h2><div className="quickAmounts">{[5000,10000,25000,50000].map(x=><button type="button" key={x} className={amount===x?'active':''} onClick={()=>setAmount(x)}>{money(x)}</button>)}</div><label><small>OTRO MONTO</small><div><b>$</b><input type="number" min="1000" max="2000000" step="100" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div></label><button className="mpButton" disabled={paying||amount<1000}>{paying?'Abriendo Mercado Pago…':'Cargar con Mercado Pago →'}</button><p className="configState">{data?.paymentsConfigured?'✓ Mercado Pago configurado':'Modo preparación · faltan credenciales privadas'}</p></form><section className="historyCard"><div className="historyHead"><span>MOVIMIENTOS</span><b>{data?.entries.length||0}</b></div>{data?.entries.slice(0,12).map(e=><div className="entry" key={e.id}><div><b>{e.kind==='topup'?'Carga de saldo':e.kind==='ojo_bid'?'Puja Ojo Acá':e.kind==='credit'?'Crédito':'Ajuste'}</b><small>{date(e.created_at)}</small></div><strong className={e.delta_minor>=0?'positive':'negative'}>{e.delta_minor>=0?'+':''}{money(e.delta_minor)}</strong></div>)}{!loading&&!data?.entries.length&&<div className="noEntries">Todavía no hay movimientos.</div>}</section></div><section className="topupHistory"><div><span>ÚLTIMAS CARGAS</span><h2>Mercado Pago.</h2></div><div>{data?.topups.slice(0,8).map(t=><article key={t.id}><b>{money(t.amount_minor)}</b><span>{t.status.toUpperCase()}</span><small>{date(t.created_at)}</small>{t.status==='pending'&&t.init_point&&<a href={t.init_point}>Retomar pago ↗</a>}</article>)}{!loading&&!data?.topups.length&&<p>No hay cargas todavía.</p>}</div></section></main>
}
