'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import './style.css';

type Profile={slug:string;display_name:string|null;bio:string|null;instagram_url:string|null;website_url:string|null};
export default function MiPerfil(){
  const [slug,setSlug]=useState('');const [name,setName]=useState('');const [bio,setBio]=useState('');const [instagram,setInstagram]=useState('');const [website,setWebsite]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [needsAuth,setNeedsAuth]=useState(false);
  useEffect(()=>{const token=localStorage.getItem('cm_access_token');if(!token){setNeedsAuth(true);setLoading(false);return}fetch('/api/cm/profile',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(r.status===401){setNeedsAuth(true);return null}return r.ok?r.json():Promise.reject()}).then(x=>{const p=x?.data as Profile|null;if(p){setSlug(p.slug||'');setName(p.display_name||'');setBio(p.bio||'');setInstagram(p.instagram_url||'');setWebsite(p.website_url||'')}}).catch(()=>setMessage('No pudimos cargar tu perfil.')).finally(()=>setLoading(false))},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();const token=localStorage.getItem('cm_access_token');if(!token)return;setSaving(true);setMessage('');const r=await fetch('/api/cm/profile',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({slug,displayName:name,bio,instagram,website})});const x=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setMessage(x?.error==='slug_taken'?'Ese nombre ya está usado. Probá otro.':'No pudimos guardar el perfil.');return}setSlug(x.data.slug);setMessage('Perfil guardado.')};
  if(needsAuth)return <main className="profileEdit"><header className="profileTop"><Link href="/che-mira-v5">CHE, MIRÁ</Link></header><section className="profileEmpty"><h1>Necesitás entrar.</h1><Link href="/che-mira-v5/acceso?next=/che-mira-v5/mi-perfil">Entrar →</Link></section></main>;
  return <main className="profileEdit"><header className="profileTop"><Link href="/che-mira-v5" className="profileLogo">CHE, MIRÁ</Link><nav><Link href="/che-mira-v5/mis-publicaciones">Mis publicaciones</Link>{slug&&<Link href={`/che-mira-v5/o/${slug}`}>Ver perfil ↗</Link>}</nav></header><section className="profileHero"><span>PERFIL DEL ORGANIZADOR</span><h1>Tu agenda pública.</h1><p>Una página simple para que uses CHE, MIRÁ como link de agenda aunque todavía no tengas audiencia acá.</p></section>{loading?<section className="profileCard">Cargando…</section>:<form className="profileCard" onSubmit={submit}><label><b>Nombre visible</b><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. La Gruta"/></label><label><b>Tu URL</b><div className="slugInput"><span>comevisit.vercel.app/che-mira-v5/o/</span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="la-gruta"/></div></label><label><b>Descripción</b><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={240} placeholder="Qué hacés, qué tipo de planes publicás, dónde."/></label><div className="profileCols"><label><b>Instagram</b><input type="url" value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="https://instagram.com/..."/></label><label><b>Web</b><input type="url" value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..."/></label></div>{message&&<p className="profileMessage">{message}</p>}<div className="profileActions"><button disabled={saving||slug.length<3}>{saving?'Guardando…':'Guardar perfil →'}</button>{slug&&<Link href={`/che-mira-v5/o/${slug}`}>Abrir agenda pública ↗</Link>}</div></form>}</main>
}
